# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b84a8563f17500bc324aafec47869269c31e440d8880ac8c8f111a8e66ded1708239ddb5c28ca1ba59bf179ae0b8e5bd06daefdff77fa47f00e8309ec5cc9a6
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  aws_s3_bucket:  <%= ENV["AWS_BUCKET"] %>


test:
  secret_key_base: ba4aa8a7cbd4f1e0251add80a5c953804347136807413cdfe58f858cb827d68e16b6cc1887ec84a64b587a2078b1e9bda44811a56e7aa6504f4ac7c0e1635eb6
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  aws_s3_bucket:  <%= ENV["AWS_BUCKET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  aws_s3_bucket:  <%= ENV["AWS_BUCKET"] %>
